from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from difflib import SequenceMatcher
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

try:
    import yaml
except ImportError:  # pragma: no cover - depends on runtime environment
    yaml = None

from .standards import normalize_path_text


PLACEHOLDER_PATTERNS = [
    re.compile(pattern, re.IGNORECASE)
    for pattern in [
        r"\bTODO\b",
        r"\bTBD\b",
        r"\bFIXME\b",
        r"待补充",
        r"待完善",
        r"placeholder",
    ]
]
MOCK_SIGNATURE_PATTERNS = [
    re.compile(pattern, re.IGNORECASE)
    for pattern in [
        r"generated by gemini mock server",
        r"\bmock[- ]?llm\b",
        r"\bmock data\b",
        r"\bmock response\b",
    ]
]
MIN_MARKDOWN_SUBSTANCE_CHARS = 120
MIN_MARKDOWN_STRUCTURED_SECTION_COUNT = 2
GENERIC_CONTEXT_HEADING_RE = re.compile(
    r"(背景|概述|概要|目标|范围|总体|综述|overview|summary|scope)",
    re.IGNORECASE,
)
MERMAID_DIAGRAM_PREFIXES = (
    "graph ",
    "flowchart ",
    "sequencediagram",
    "classdiagram",
    "statediagram",
    "statediagram-v2",
    "erdiagram",
    "journey",
    "gantt",
    "pie ",
    "mindmap",
    "timeline",
    "quadrantchart",
    "requirementdiagram",
    "c4context",
    "c4container",
    "c4component",
    "c4dynamic",
    "c4deployment",
)


@dataclass
class ArtifactScope:
    capability: str
    selected_outputs: List[str]


def validate_artifacts(root_dir: Path, tool_input: Dict[str, Any]) -> Dict[str, Any]:
    project_root = root_dir.resolve()
    artifacts_dir = project_root / "artifacts"
    evidence_dir = project_root / "evidence"
    evidence_dir.mkdir(parents=True, exist_ok=True)

    scoped_outputs = _load_selected_outputs(artifacts_dir)
    selected_outputs = _dedupe_preserve_order(
        output
        for scope in scoped_outputs
        for output in scope.selected_outputs
    )
    output_owner_map = {
        output: scope.capability
        for scope in scoped_outputs
        for output in scope.selected_outputs
    }

    requested_targets = _normalize_requested_targets(tool_input.get("target_files"))
    if requested_targets:
        files_to_check = requested_targets
    elif selected_outputs:
        files_to_check = list(selected_outputs)
    else:
        files_to_check = _discover_artifact_files(artifacts_dir)

    findings: List[Dict[str, Any]] = []

    for relative_output in selected_outputs:
        target_path = artifacts_dir / relative_output
        if not target_path.exists():
            findings.append(
                _finding(
                    check_id="missing_selected_output",
                    severity="error",
                    file=f"artifacts/{relative_output}",
                    message="Selected output is missing from this run.",
                    evidence={"capability": output_owner_map.get(relative_output)},
                    auto_fixable=False,
                    repair_mode="manual",
                    approval_required=True,
                    owner_expert=output_owner_map.get(relative_output),
                )
            )

    checked_files: List[str] = []
    for relative_output in files_to_check:
        normalized_output = _normalize_artifact_relative_path(relative_output)
        target_path = artifacts_dir / normalized_output
        if not target_path.exists() or not target_path.is_file():
            continue
        checked_files.append(f"artifacts/{normalized_output}")
        owner_expert = output_owner_map.get(normalized_output)
        findings.extend(_validate_file(target_path, normalized_output, owner_expert))

    findings_path = evidence_dir / "validator-findings.json"
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "root_dir": str(project_root),
        "selected_outputs": [f"artifacts/{item}" for item in selected_outputs],
        "checked_files": checked_files,
        "summary": _summarize_findings(findings),
        "limitations": [
            "Mermaid checks are heuristic smoke tests in this first version; they do not execute the frontend renderer.",
            "Near-duplicate detection is section-level and markdown-focused; it does not yet rewrite or relocate content automatically.",
        ],
        "findings": findings,
    }
    findings_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    return {
        "root_dir": str(project_root),
        "findings_path": findings_path.relative_to(project_root).as_posix(),
        "selected_outputs": [f"artifacts/{item}" for item in selected_outputs],
        "checked_files": checked_files,
        "summary": payload["summary"],
        "findings": findings,
    }


def _load_selected_outputs(artifacts_dir: Path) -> List[ArtifactScope]:
    work_dir = artifacts_dir / "_work"
    scopes: List[ArtifactScope] = []
    if not work_dir.exists():
        return scopes

    for capability_dir in sorted(path for path in work_dir.iterdir() if path.is_dir()):
        output_plan_path = capability_dir / "output-plan.json"
        if not output_plan_path.exists():
            continue
        try:
            data = json.loads(output_plan_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue

        selected_outputs = _dedupe_preserve_order(
            _normalize_artifact_relative_path(item)
            for item in (data.get("selected_outputs") or [])
            if isinstance(item, str) and item.strip()
        )
        if not selected_outputs:
            continue
        scopes.append(
            ArtifactScope(
                capability=capability_dir.name,
                selected_outputs=selected_outputs,
            )
        )
    return scopes


def _discover_artifact_files(artifacts_dir: Path) -> List[str]:
    if not artifacts_dir.exists():
        return []
    return [
        item.relative_to(artifacts_dir).as_posix()
        for item in sorted(artifacts_dir.iterdir())
        if item.is_file()
    ]


def _normalize_requested_targets(raw_value: Any) -> List[str]:
    values: List[str]
    if raw_value is None:
        return []
    if isinstance(raw_value, str):
        values = [raw_value]
    elif isinstance(raw_value, list):
        values = [item for item in raw_value if isinstance(item, str)]
    else:
        return []
    return _dedupe_preserve_order(
        _normalize_artifact_relative_path(item)
        for item in values
        if item.strip()
    )


def _normalize_artifact_relative_path(raw_value: str) -> str:
    normalized = normalize_path_text(raw_value)
    if normalized.startswith("artifacts/"):
        return normalized.split("/", 1)[1]
    return normalized


def _validate_file(file_path: Path, relative_output: str, owner_expert: Optional[str]) -> List[Dict[str, Any]]:
    suffix = file_path.suffix.lower()
    findings: List[Dict[str, Any]] = []
    text = file_path.read_text(encoding="utf-8", errors="replace")
    display_path = f"artifacts/{relative_output}"

    if not text.strip():
        findings.append(
            _finding(
                check_id="empty_artifact",
                severity="error",
                file=display_path,
                message="Artifact exists but is empty.",
                auto_fixable=False,
                repair_mode="manual",
                approval_required=True,
                owner_expert=owner_expert,
            )
        )
        return findings

    mock_hits = _detect_mock_signatures(text, suffix)
    if mock_hits:
        findings.append(
            _finding(
                check_id="mock_generated_content",
                severity="error",
                file=display_path,
                message="Artifact appears to be mock/generated placeholder content and cannot pass delivery validation.",
                evidence={"signals": mock_hits[:8]},
                auto_fixable=False,
                repair_mode="llm_proposal",
                approval_required=True,
                owner_expert=owner_expert,
            )
        )

    placeholder_hits = sorted({match.group(0) for match in _iter_placeholder_matches(text)})
    if placeholder_hits:
        findings.append(
            _finding(
                check_id="placeholder_content",
                severity="warning",
                file=display_path,
                message="Artifact still contains placeholder markers.",
                evidence={"tokens": placeholder_hits[:8]},
                auto_fixable=False,
                repair_mode="llm_proposal",
                approval_required=True,
                owner_expert=owner_expert,
            )
        )

    if suffix == ".md":
        findings.extend(_validate_markdown(text, display_path, owner_expert))
    elif suffix == ".json":
        findings.extend(_validate_json(text, display_path, owner_expert))
    elif suffix in {".yaml", ".yml"}:
        findings.extend(_validate_yaml(text, display_path, owner_expert))

    return findings


def _validate_markdown(content: str, display_path: str, owner_expert: Optional[str]) -> List[Dict[str, Any]]:
    findings: List[Dict[str, Any]] = []

    if content.count("```") % 2 != 0:
        findings.append(
            _finding(
                check_id="markdown_unclosed_fence",
                severity="error",
                file=display_path,
                message="Markdown fenced code blocks are not balanced.",
                auto_fixable=True,
                repair_mode="safe_auto_fix",
                approval_required=False,
                owner_expert=owner_expert,
            )
        )

    sections = _extract_markdown_sections(content)
    normalized_substance = _normalize_body_text(content)
    if (
        len(normalized_substance) < MIN_MARKDOWN_SUBSTANCE_CHARS
        and len(sections) < MIN_MARKDOWN_STRUCTURED_SECTION_COUNT
    ):
        findings.append(
            _finding(
                check_id="markdown_insufficient_substance",
                severity="error",
                file=display_path,
                message="Markdown artifact is too short and lacks minimum section structure for executable design handoff.",
                evidence={
                    "normalized_char_count": len(normalized_substance),
                    "section_count": len(sections),
                    "minimum_char_count": MIN_MARKDOWN_SUBSTANCE_CHARS,
                    "minimum_section_count": MIN_MARKDOWN_STRUCTURED_SECTION_COUNT,
                },
                auto_fixable=False,
                repair_mode="llm_proposal",
                approval_required=True,
                owner_expert=owner_expert,
            )
        )

    normalized_heading_counts: Dict[str, int] = {}
    for section in sections:
        heading_key = _normalize_text_key(section["heading"])
        if heading_key:
            normalized_heading_counts[heading_key] = normalized_heading_counts.get(heading_key, 0) + 1

    duplicate_titles = [section["heading"] for section in sections if normalized_heading_counts.get(_normalize_text_key(section["heading"]), 0) > 1]
    duplicate_titles = _dedupe_preserve_order(duplicate_titles)
    if duplicate_titles:
        findings.append(
            _finding(
                check_id="markdown_duplicate_heading",
                severity="warning",
                file=display_path,
                message="Markdown contains duplicate section headings.",
                evidence={"headings": duplicate_titles[:10]},
                auto_fixable=True,
                repair_mode="safe_auto_fix",
                approval_required=False,
                owner_expert=owner_expert,
            )
        )

    near_duplicates = _find_near_duplicate_sections(sections)
    for item in near_duplicates:
        findings.append(
            _finding(
                check_id="markdown_near_duplicate_section",
                severity="warning",
                file=display_path,
                heading=item["candidate_heading"],
                message="Markdown contains near-duplicate section content.",
                evidence=item,
                auto_fixable=False,
                repair_mode="llm_proposal",
                approval_required=True,
                owner_expert=owner_expert,
            )
        )

    generic_context_headings = [
        section["heading"]
        for section in sections
        if GENERIC_CONTEXT_HEADING_RE.search(section["heading"])
    ]
    if len(generic_context_headings) >= 2:
        findings.append(
            _finding(
                check_id="generic_context_overuse",
                severity="info",
                file=display_path,
                message="Markdown contains multiple generic background or scope sections; this often correlates with duplicated narrative.",
                evidence={"headings": generic_context_headings[:8]},
                auto_fixable=False,
                repair_mode="llm_proposal",
                approval_required=True,
                owner_expert=owner_expert,
            )
        )

    findings.extend(_validate_mermaid_blocks(content, display_path, owner_expert))
    return findings


def _validate_json(content: str, display_path: str, owner_expert: Optional[str]) -> List[Dict[str, Any]]:
    try:
        json.loads(content)
        return []
    except json.JSONDecodeError as exc:
        return [
            _finding(
                check_id="json_parse_error",
                severity="error",
                file=display_path,
                message="JSON artifact cannot be parsed.",
                evidence={"line": exc.lineno, "column": exc.colno, "error": str(exc)},
                auto_fixable=True,
                repair_mode="safe_auto_fix",
                approval_required=False,
                owner_expert=owner_expert,
            )
        ]


def _validate_yaml(content: str, display_path: str, owner_expert: Optional[str]) -> List[Dict[str, Any]]:
    if yaml is None:
        return [
            _finding(
                check_id="yaml_validation_unavailable",
                severity="info",
                file=display_path,
                message="YAML validation skipped because PyYAML is not installed in the current runtime.",
                auto_fixable=False,
                repair_mode="manual",
                approval_required=False,
                owner_expert=owner_expert,
                confidence=0.99,
            )
        ]
    try:
        yaml.safe_load(content)
        return []
    except Exception as exc:
        return [
            _finding(
                check_id="yaml_parse_error",
                severity="error",
                file=display_path,
                message="YAML artifact cannot be parsed.",
                evidence={"error": str(exc)},
                auto_fixable=True,
                repair_mode="safe_auto_fix",
                approval_required=False,
                owner_expert=owner_expert,
            )
        ]


def _validate_mermaid_blocks(content: str, display_path: str, owner_expert: Optional[str]) -> List[Dict[str, Any]]:
    findings: List[Dict[str, Any]] = []
    mermaid_blocks = _extract_mermaid_blocks(content)

    for index, block in enumerate(mermaid_blocks, start=1):
        lines = [line.rstrip() for line in block.splitlines() if line.strip()]
        if not lines:
            findings.append(
                _finding(
                    check_id="mermaid_empty_block",
                    severity="warning",
                    file=display_path,
                    message="Mermaid block is empty.",
                    evidence={"block_index": index},
                    auto_fixable=True,
                    repair_mode="safe_auto_fix",
                    approval_required=False,
                    owner_expert=owner_expert,
                )
            )
            continue

        first_line = lines[0].strip().lower()
        if not first_line.startswith(MERMAID_DIAGRAM_PREFIXES):
            findings.append(
                _finding(
                    check_id="mermaid_missing_diagram_prefix",
                    severity="error",
                    file=display_path,
                    message="Mermaid block does not start with a recognized diagram declaration.",
                    evidence={"block_index": index, "first_line": lines[0].strip()},
                    auto_fixable=False,
                    repair_mode="llm_proposal",
                    approval_required=True,
                    owner_expert=owner_expert,
                )
            )

        subgraph_count = sum(1 for line in lines if line.strip().lower().startswith("subgraph "))
        end_count = sum(1 for line in lines if line.strip().lower() == "end")
        if subgraph_count != end_count:
            findings.append(
                _finding(
                    check_id="mermaid_subgraph_balance",
                    severity="error",
                    file=display_path,
                    message="Mermaid subgraph blocks are not balanced.",
                    evidence={"block_index": index, "subgraph_count": subgraph_count, "end_count": end_count},
                    auto_fixable=False,
                    repair_mode="llm_proposal",
                    approval_required=True,
                    owner_expert=owner_expert,
                )
            )

        unmatched_fence_markers = sum(1 for line in block.splitlines() if line.strip().startswith("```"))
        if unmatched_fence_markers:
            findings.append(
                _finding(
                    check_id="mermaid_embedded_fence_marker",
                    severity="warning",
                    file=display_path,
                    message="Mermaid block contains nested fence markers that may break frontend rendering.",
                    evidence={"block_index": index},
                    auto_fixable=True,
                    repair_mode="safe_auto_fix",
                    approval_required=False,
                    owner_expert=owner_expert,
                )
            )

    return findings


def _extract_mermaid_blocks(content: str) -> List[str]:
    pattern = re.compile(r"```mermaid\s*\n(.*?)\n```", re.IGNORECASE | re.DOTALL)
    return [match.group(1) for match in pattern.finditer(content)]


def _extract_markdown_sections(content: str) -> List[Dict[str, Any]]:
    sections: List[Dict[str, Any]] = []
    current_heading: Optional[str] = None
    current_level = 0
    current_lines: List[str] = []

    for raw_line in content.splitlines():
        match = re.match(r"^\s*(#{1,6})\s+(.+?)\s*$", raw_line)
        if match:
            if current_heading is not None:
                sections.append(
                    {
                        "heading": current_heading,
                        "level": current_level,
                        "body": "\n".join(current_lines).strip(),
                    }
                )
            current_heading = match.group(2).strip()
            current_level = len(match.group(1))
            current_lines = []
            continue
        if current_heading is not None:
            current_lines.append(raw_line)

    if current_heading is not None:
        sections.append(
            {
                "heading": current_heading,
                "level": current_level,
                "body": "\n".join(current_lines).strip(),
            }
        )
    return sections


def _find_near_duplicate_sections(sections: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    findings: List[Dict[str, Any]] = []
    for index, candidate in enumerate(sections):
        candidate_body = _normalize_body_text(candidate["body"])
        if len(candidate_body) < 80:
            continue
        for previous in sections[:index]:
            previous_body = _normalize_body_text(previous["body"])
            if len(previous_body) < 80:
                continue
            similarity = _similarity_ratio(candidate_body, previous_body)
            if similarity < 0.9:
                continue
            findings.append(
                {
                    "candidate_heading": candidate["heading"],
                    "existing_heading": previous["heading"],
                    "similarity": round(similarity, 4),
                }
            )
            break
    return findings


def _normalize_body_text(text: str) -> str:
    normalized = re.sub(r"`[^`]+`", " ", str(text or ""))
    normalized = re.sub(r"^\s*[-*]\s+", "", normalized, flags=re.MULTILINE)
    normalized = re.sub(r"^\s*\d+[.)]\s*", "", normalized, flags=re.MULTILINE)
    normalized = re.sub(r"[^a-zA-Z0-9\u4e00-\u9fff]+", " ", normalized)
    return re.sub(r"\s+", " ", normalized).strip().lower()


def _similarity_ratio(text_a: str, text_b: str) -> float:
    if not text_a or not text_b:
        return 0.0
    if text_a == text_b:
        return 1.0
    shorter_length = min(len(text_a), len(text_b))
    if shorter_length >= 80 and (text_a in text_b or text_b in text_a):
        return 0.99
    return SequenceMatcher(None, text_a[:4000], text_b[:4000]).ratio()


def _iter_placeholder_matches(content: str) -> Iterable[re.Match[str]]:
    for pattern in PLACEHOLDER_PATTERNS:
        for match in pattern.finditer(content):
            yield match


def _detect_mock_signatures(content: str, suffix: str) -> List[str]:
    hits: List[str] = []
    for pattern in MOCK_SIGNATURE_PATTERNS:
        if pattern.search(content):
            hits.append(pattern.pattern)

    if suffix == ".json":
        try:
            payload = json.loads(content)
        except Exception:
            payload = None

        if isinstance(payload, dict):
            normalized_keys = {str(key).strip().lower() for key in payload.keys()}
            status = str(payload.get("status", "")).strip().lower()
            if "mock" in normalized_keys and status == "generated":
                hits.append("json_mock_status_generated")

    return _dedupe_preserve_order(hits)


def _normalize_text_key(text: str) -> str:
    normalized = str(text or "").strip().lower()
    normalized = re.sub(r"[^a-zA-Z0-9\u4e00-\u9fff]+", " ", normalized)
    return re.sub(r"\s+", " ", normalized).strip()


def _finding(
    *,
    check_id: str,
    severity: str,
    file: str,
    message: str,
    evidence: Optional[Dict[str, Any]] = None,
    auto_fixable: bool,
    repair_mode: str,
    approval_required: bool,
    owner_expert: Optional[str],
    heading: Optional[str] = None,
    candidate_target_experts: Optional[List[str]] = None,
    confidence: float = 0.9,
) -> Dict[str, Any]:
    return {
        "check_id": check_id,
        "severity": severity,
        "file": file,
        "heading": heading,
        "message": message,
        "evidence": evidence or {},
        "auto_fixable": auto_fixable,
        "repair_mode": repair_mode,
        "approval_required": approval_required,
        "owner_expert": owner_expert,
        "candidate_target_experts": candidate_target_experts or ([] if owner_expert is None else [owner_expert]),
        "confidence": confidence,
    }


def _summarize_findings(findings: List[Dict[str, Any]]) -> Dict[str, int]:
    return {
        "errors": sum(1 for item in findings if item.get("severity") == "error"),
        "warnings": sum(1 for item in findings if item.get("severity") == "warning"),
        "infos": sum(1 for item in findings if item.get("severity") == "info"),
        "total": len(findings),
    }


def _dedupe_preserve_order(items: Iterable[str]) -> List[str]:
    seen: set[str] = set()
    ordered: List[str] = []
    for item in items:
        if item and item not in seen:
            seen.add(item)
            ordered.append(item)
    return ordered
